name: esc
description: Easy SSH Connection
version: 1.0.0
publish_to: none
repository: https://github.com/arifai/esc

environment:
  sdk: ^3.1.3

executables:
  esc: esc

dependencies:
  args: ^2.4.2
  dartssh2: 
    git:
      url: https://github.com/anyliker/dartssh2.git
      ref: master
  equatable: ^2.0.5
  io: ^1.0.4
  yaml: ^3.1.2
  yaml_edit: ^2.1.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
