name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout ${{ github.ref }} branch in ${{ github.repository }} repository
        uses: actions/checkout@v4

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1.6.0
        with:
          sdk: stable
      
      - name: Install dependencies
        run: dart pub get
      
      - name: Create a new tag
        run: git tag ${{ github.event.inputs.version }}

      - name: Ready to build
        run: dart compile exe bin/esc.dart -o /tmp/esc

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ github.event.release.tag_name }}
          path: /tmp/esc